AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/**/*
    - bin/**/*
    - tmp/**/*
    - lib/patches/class_methods.rb
    - config.ru

Metrics/LineLength:
  Max: 95

Metrics/ClassLength:
  Max: 150

Style/Documentation:
  Enabled: false

Style/PredicateName:
  NamePrefix:
    - is_
    - have_
  NamePrefixBlacklist:
    - is_
    - have_

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/FrozenStringLiteralComment:
  Enabled: false